### ISSUE TITLE
Github deprecation warning message 

### ISSUE THREAD

**Issue by asafwat** [xt0rted/pull-request-comment-branch#340]
hi,

i am getting the below GitHub node 12 deprecation message  although i am using the latest version 1.4.0

`Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: xt0rted/pull-request-comment-branch@v1.4.0. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.`

and here is how it looks in the workflow 

- name: Extract PR info
        uses: xt0rted/pull-request-comment-branch@v1.4.0
        id: comment-branch
        with:
          repo_token: ${{ steps.generate_token.outputs.token }}
          
any idea?
thanks

**Comment by sashuk** [comment]
Hello, @asafwat! I confirm the same problem

<img width="1089" alt="Screenshot 2023-03-17 at 14 17 28" src="https://user-images.githubusercontent.com/1390758/225890187-f05e8c68-589f-4332-b913-42b762261609.png">

**Comment by xt0rted** [comment]
I just released v2 so you shouldn't see this warning anymore once you update your workflows.
