### ISSUE TITLE
Update Node.js to 20

### ISSUE THREAD

**Issue by massongit** [xt0rted/pull-request-comment-branch#418]
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

Node.js 16 actions are deprecated.
Therefore, you need to update Node.js used in this Action to 20.

**Comment by skoonin** [comment]
@xt0rted thanks for your work on this, my job still uses this action.  any chance you are able to review and release this sometime soon? 🙇‍♂️

**Comment by gugaiz** [comment]
I think he already changed, but it is not tagged

**Comment by gugaiz** [comment]
I found that the dist folder is not part of the repo, so it is not a matter of pointing to main

**Comment by Sec-ant** [comment]
Hey @xt0rted, my workflow relys on this action very much. I would be really appreciate if you can update nodejs to 20.

**Comment by kishaningithub** [comment]
@xt0rted Would be great if this can be done ASAP

**Comment by skoonin** [comment]
thank you!

**Comment by massongit** [comment]
Thank you for new release!
