### ISSUE TITLE
Get base branch information

### ISSUE THREAD

**Issue by taha-husain** [xt0rted/pull-request-comment-branch#68]
I use this action to fetch ref branch name and a separate logic to fetch base branch name. It would be nice to get base branch name from this action.

**Comment by xt0rted** [comment]
I just published v1.2.0 which includes the base ref & sha now. This also deprecated the `ref` & `sha` values in favor of `head_ref` and `head_sha` to match the new `base_*` values. Hope this helps.

**Comment by taha-husain** [comment]
Thanks for this @xt0rted 🎉
